branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Not really necessary, just to get a green badge on “master”
    - master
language: rust
os: linux
dist: focal
addons:
  apt:
    sources:
    - sourceline: "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main"
      key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    packages:
    - clang-11
    - cmake
rust:
   - stable
cache: cargo
env:
  global:
    - RUST_BACKTRACE=1
jobs:
  include:
    # Matrix build of 3 targets against Rust stable
    - rust: stable
      env: TARGET=x86_64-unknown-linux-gnu AES_NI_SUPPORT=true
    - rust: stable
      env: TARGET=aarch64-unknown-linux-gnu
      arch: arm64
    - rust: stable
      env: TARGET=x86_64-fortanix-unknown-sgx
    # Test additional Rust toolchains on x86_64
    - rust: beta
      env: TARGET=x86_64-unknown-linux-gnu AES_NI_SUPPORT=true
    - rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu AES_NI_SUPPORT=true
script:
  - ./ct.sh
